#### Astrocyte Parameter sets
astro_plasticity: &astro_plasticity
  mode: plasticity
    
  tau_ca: 50.0
  ca_th: 100000.0

  tau_ip3: 100.0
  alpha_ip3: 1.0
  pre_reset_on_spike: False

  tau_kp: 100.0
  alpha_kp: 1.0
  post_reset_on_spike: False
  
  ordered_prod:
    ltd: 0.0
    dw_ltd: 0.95
    ltp: 0.0
    dw_ltp: 1.05

  dw_mult:
    prop_ca: False
    dw_ltd: 0.95
    dw_ltp: 1.05

  dw: null

  local:
    stdp: null
    ca_thr: null
    ordered_prod: null
    ip3_ca: null
    
  coupling:
    and: null
    nand: null


anti_stdp: &anti_stdp
  __inherit__: *astro_plasticity
  alpha_ip3: -1.0
  alpha_kp: -1.0

ltp_bias: &ltp_bias
  __inherit__: *astro_plasticity
  tau_ip3: 30

ltd_bias: &ltd_bias
  __inherit__: *astro_plasticity
  tau_kp: 30

ltp_dt_shift: &ltp_dt_shift
  __inherit__: *astro_plasticity
  u_step_params:
    ltd: -0.5
    ltp: -0.5

ltd_dt_shift: &ltd_dt_shift
  __inherit__: *astro_plasticity
  u_step_params:
    ltp: 0.5
    ltd: 0.5

sim:
  dt: 0.001
  steps: 200

linear_params:
  synapse: 1
  init: 'normal'
  mu: 0.7
  sigma: 0.001
  min: -20.0
  max: 20.0

nice_lif_params: &nice_lif_params
  v_reset: -0.2
  v_leak: 0.0
  v_th: 0.2
  method: 'heaviside'
  alpha: 1.0  # doesn't matter if ^ is heaviside, see threshold.py
  tau_mem: 60.0
  tau_syn: 500.0  # 1000 means no memory, since the entire value of i will decay each step


# Parameter sets
astro_params: null
lif_params: *nice_lif_params
