#### Astrocyte Parameter sets
astro_plasticity: &astro_plasticity
  mode: plasticity
    
  tau_ca: 50.0
  ca_th: 100000.0

  tau_ip3: 100.0
  alpha_ip3: 1.0
  pre_reset_on_spike: False

  tau_kp: 100.0
  alpha_kp: 1.0
  post_reset_on_spike: False
  
  ordered_prod:
    ltd: 0.0
    dw_ltd: 0.95
    ltp: 0.0
    dw_ltp: 1.05

  dw: dw_mult

  dw_mult:
    prop_ca: false
    dw_ltd: 0.95
    dw_ltp: 1.05

  stdp:
    # Defaults should be large to not effect default behavior
    ltp: 1000.0
    ltd: 1000.0

  local:
    stdp: null
    ca_thr: null
    prop: null
    ordered_prod: null
    ip3_ca: null
    
  coupling:
    and: null
    nand: null


anti_stdp: &anti_stdp
  __inherit__: *astro_plasticity
  alpha_ip3: -1.0
  alpha_kp: -1.0


#### LIF Parameter sets ####
nice_lif_params: &nice_lif_params
  v_reset: -0.2
  v_leak: 0.0
  v_th: 0.2
  method: 'heaviside'
  alpha: 1.0  # doesn't matter if ^ is heaviside, see threshold.py
  tau_mem: 60.0
  tau_syn: 500.0  # 1000 means no memory, since the entire value of i will decay each step

sim:
  dt: 0.001
  steps: 200

linear_params:
  init: normal
  synapse: 1
  mu: 0.7
  sigma: 0.001
  min: -20.0
  max: 20.0

astro_params: null
lif_params: *nice_lif_params
