#### Astrocyte Parameter sets
classic_stdp: &classic_stdp
  mode: plasticity
    
  tau_ca: 50.0
  ca_th: 2.5

  and_th: 0.5
  and_ltp_th: 0.01

  tau_ip3: 100.0
  alpha_pre: 1.0
  pre_reset_on_spike: False

  tau_kp: 100.0
  alpha_post: 1.0
  post_reset_on_spike: False

  dca_max: 100000.0
  weight_update: prop

  u_step_params:
    mode: stdp
    ltd: 0.0
    dw_ltd: 0.95

    ltp: 0.0
    dw_ltp: 1.05


anti_stdp: &anti_stdp
  __inherit__: *classic_stdp
  alpha_pre: -1.0
  alpha_post: -1.0


astro_plasticity:
  tau_ca: 50.0
  ca_th: 2.5
  
  and_th: 0.5
  and_ltp_th: 0.09

  tau_ip3: 80.0
  alpha_ip3: 1.0
  pre_reset_on_spike: False

  tau_kp: 80.0
  alpha_kp: 1.2
  post_reset_on_spike: False

  dw_mult: &dw_mult
    ltd: 0.0
    dw_ltd: 0.03

    ltp: 0.0
    dw_ltp: 0.2
    
  dw_add: &dw_add
    ltd: 0.0
    dw_ltd: 0.01

    ltp: 0.0
    dw_ltp: 0.1

  dw: dw_mult

  stdp:
    # Defaults should be large to not effect default behavior
    ltp: 1000.0
    ltd: 1000.0

  local:
    stdp: [0, 1, 2, 3, 4, 5, 6, 7, 8]
    ip3_ca: [0, 1, 2, 3, 4, 5, 6, 7, 8]

  coupling:
    and: null
    nand: null

  dca_max: 100000.0

  weight_update: thr
  ip3_kp_activity_thr: 0.2


#### LIF Parameter sets ####
nice_lif_params: &nice_lif_params
  v_reset: -0.4
  v_leak: 0.0
  v_th: 0.2
  method: 'heaviside'
  alpha: 1.0  # doesn't matter if ^ is heaviside, see threshold.py
  tau_mem: 350.0
  tau_syn: 600.0  # 1000 means no memory, since the entire value of i will decay each step

sim:
  dt: 0.001
  dw: True
  steps: 200

linear_params:
  synapse: 2
  init: 'normal'
  mu: 0.7
  sigma: 0.001
  min: -20.0
  max: 20.0


astro_params: null
lif_params: *nice_lif_params
