* Random Thoughts
I eventually want to settle on a RL task that has something to do with survival. An example is
a feed and hide process with different sensory input. The organism has to decide between feeding
and hiding based on visual and auditory input. In a 1-D space there could be food moving towards
it, or a predator.

Astrocytes role in short-term memory and focus (if such a role exists, this is speculation) may
necessitate a more complex task. For example, one thought I had is that astrocytes can select a
subset of a network most suited to the task at hand, and keep this subnet active for the duration
that it is needed. This

There may be an application of astrocytes in imitation (this would be related to working memory).
Mirror neurons become active during an observed action, astrocytes integrate their activity and
hold a state, when the network goes to perform said action, and the same neurons light up a reward
could be generated by the astrocytes.
After some more thought
An observer network could be trained to output on 1-n neurons when 1-n actions are observed. There
are another 1-n action neurons, corresponding to the same 1-n actions. When A mirror neuron and action
neuron fire in close temporal proximity a reward signal is propagated through the network. The
"close temporal proximity" is determined by an astrocyte.

What if astrocytes modulate learning, and prevent LTP until a certain level of synchronous firing
is attained. A good experiment would be to present a synchronous burst along some subset of
synapses at some regular interval, but the rest of the time there is noise on all inputs. The hypothesis
is that LTD would depress synapses until the synchrony made its way through.

yet another working memory problem. Show that a spiking network w/ astrocytes could solve, or learn to
solve N-Back, where SNN alone couldn't

What if STDP is meant to drive STD/STP, and astrocytes govern how long the
transient weight change lasts. The astrocyte could also effect if the short-term
change becomes permanent.

** Error Propagation
Could astrocytes be responsible for the propagation of errors in a multi-layer
setup? For example: Say we have a two layer network, where N1 and N2 connect to N0
N1 ---> N0
N2 -----/

We could apply some reward (or punishment) when the output is undesirable...OR
we could apply a teaching signal at N0, force it's value to the proper
state. When there is a teaching signal at the output, could astrocytes help this
signal propagate back across the network?


* Current Best Theories
** Activity modulation

** Plasticity
*** Sync-based mod of learning and activity
Astrocytes modulate learning based on synchronous firing, filtering out noise in the learning
process, and training the network to propagate synchronous input. In a similar fashion, astrocytes
could respond to synchronous activity with weight modulation, allowing sync inputs to be propagated
to the output.

[[5]],

*** Conversion from influence to long-term weight change
Subthreshold increases in Ca results in SICs, which bias post-synaptic neuron to
fire. based on activity, or maybe Ca2+ levels, SIC is ceased, and weight update
commences.

*** Auto-encoding
It is well known that there are populations of neurons that encode the physical
world via some sensory input (hearing, vision, etc...) perhaps astrocytes are
involved in this process.


** State holding / short-term memory
Astrocytes respond to some activity on a group of synapses, by setting an internal state. This
state then results in either increased weights, or some current injected into the system.

Could astrocytes facilitate neurons being sensitive to spike order? - In a way yes, subsequent spikes
could result in an overall dampening effect, proportional to the PSP. How would this be beneficial
regionally though? - It could make order important on a per-synapse basis for a group, instead of
per-neuron. What about across-neurons? - we'll see

This could take the form of transient weight changes that result in a new pathway.

[[2]], [[5]]


* Next
** Markam 1998
Differential signaling w/ same axon

Implements STP/STD. a,u,d,f params + a few more
Has tau_s and tau_m to form PSP

Transient long-term depression

* Experiments
** 12AX w/ recurrent network
see [2] - make the network more sparse
LIF alone achieved 0.0% accuracy

** Survival Task (feed/hide)

** Subnetwork Learning (RNN)
** State Machine

** 1N1A1S Pre -> weight delta


Single input path, single output path. 1N1A1S. Range of parameters
What is the input: Random poission spike train w/ various base frequencies
What am I looking for on output side
Speculations/Hypthosis on Astrocyte effect in current configuration


* Refs
** <<1>> - On the role of astrocytes in synchronization of two coupled neurons: a mathematical perspective

** <<2>> - Spike frequency adaptation supports network computations on temporally dispersed information
SFA has a large impact on performance when applied to a task that requires integration of
inputs in the realm of seconds. SNN would have trouble doing this alone as they operate on the
time-scale of ms - 10ms.

SFA results in negative-imprinting, where repeated patterns result in less of a response

Researchers have shown that this approach improves performance (in some cases significantly)
on tasks: Sequential MNIST, XOR, 12AX. They leveraged recurrent neural networks, and partial SFA
(40%) on these tasks.


** <<3>> - Astrocytes Control Synapse Formation, Function, and Elimination
Astrocytes facilitate the formation of synaptic connections in the developing brain. They
are also associated with synapse elimination.

Astrocytes show a tiling pattern, and for non-overlapping groups. This is thought
to be due to contact-inhibitions. If there is disease this pattern may break, and
Astrocytes will show intermingling.

One Astrocyte contacts about 100,000 synapses in Rat brains.

Astrocytes prevent NT spillover and keep synapse comms local. They also listen and respond to
synapse activity, affecting synapses in their

** <<4>> - Modeling Working Memory in a Spiking Neuron Network Accompanied by Astrocytes
The authors implemented a working memory network consisting of a SNN network interacting with an
Astrocyte network. Successful retrival of the data is possible 90% of the time, with the information
being stored for several seconds. There are overlapping pieces of memory stored in this case.

The time-scale of Astrocytes and working memory line up, suggesting they may be involved. Further
evidence supports this.
- Pathology of astrocytes in the median pre-frontal cortex impairs working memory
- Increasing astrocyte density in PFC enhances short-term memory performance

"in particular, recent in vivo studies
have shown the participation of astrocytes in the synchronization
of certain cortical network activities (Takata et al., 2011; Chen
et al., 2012; Paukert et al., 2014; Perea et al., 2014),"

"t has been experimentally estimated that there is some overlap
in the spatial territories occupied by individual astrocytes in the
cortex (Halassa et al., 2007). An individual cortical astrocyte
contacts on average 4-8 neuronal somata and 300–600 neuronal
dendrites (Halassa et al., 2007)."

Some related work explored the possibility of WM with different neuron properties or connetions.
WM was possible in both recurrent and FF architectures. Two main problems arose from these
approaches.
- There is no way to store information in the network when the neurons are in a resting
state
- Minor variations in activity destroyed the information

It is estimated that within the Pre-frontal cortex of mammals, that an individual
astroctye contacs 4-8 neuronal bodies and 600-800 dendrites.

The considered architecture consists of WxH izh spiking neurons layed out in a grid, with
connection lengths being randomly drawn from the exponential distribution. Figure 1. Astrocytes
are placed in a similar grid, with lower resolution, allowing them to contact multiple neurons
and synapses. In this work, astrocytes are only activated when there is a sufficent level of
correlated firing, specifically 0.5. At a high level, astrocyte [Ca2+] is affected by neuron activity
via a direct, and IP3 mediated pathways, as well as influx of Ca2+ from neighboring astrocytes.
This rise in [Ca2+] results in an overall potentiation of associated synapse via the following
equation.

g_{syn} = n + vCA
vCA = vCA*STEP([Ca2+] - [Ca2+]_{thr})

Simulation
A base-line level of noise is added to the system, such that there are low-level spontanious
spiking events. Numerical digits were presented to the grid of neurons during a training phase
where they were loaded into astrocyte states. After some delay, very noisy versions of the same
inputs where presented to the network, and it responded more strongly to the ones presented during
"training" vs. luer inputs.


** <<5>> - The computational power of astrocyte mediated synaptic plasticity
How do astrocytes signal back to neurons?
- Ion (K+, Na+, etc...) update modulation. This could be akin to changing the duration of a PSP
- Release of their own transmitters

What is the overall effect?

Modulation of excitability
--------------------------
There are a variety of chemical mechanisms by which astrocytes can modulate neuron excitability,
but none of these mechanisms, or the overall discusson show a clear functional role.

Short-Term Synaptic Plasticity
------------------------------
- Astrocytes can modulate synaptic strength transiently (~10s)
- This modulation can happen at a variety of levels. Glutamate release can activate receptors on
the axon, and increase Pre-synaptic release probability. This effect can spread to neighboring
synapses that share the same axon. The release of glutamate can also increase firing probability
locally.
- Astrocytes, through different transmitters, can cause short-term synaptic depression.

Long-Term Synaptic Plasticity
-----------------------------
Astrocytes appear to implement/facilitate STDP in the brain, and as such are in a good position
to regulate it. There is evidence that synaptic plasticity isn't possible until an Astrocyte is
sufficiently activated.

Possible Computational Roles
----------------------------
- Modulation of plasticity threshold. I.e. a gating control on learning
- Through modulation of excitability, and STP, astrocytes can select a particular synaptic ensamble
during processing

- Astrocyte modulation of weights has been shown to be dependant on the presence of as Pre-SP, but
not necessarily a Post-SP.

*** Interesting References
Nadkarni et al. (2008) - Optimize Pre-SP release probability w/ Astrocyte
De Pittà et al., 2011. - Astrocytes mediate the switch between pulse-paired LTD and LTP
(anti-stdp vs stdp)


** <<6>> - Astrocytes and human cognition: Modeling information integration and modulation of neuronal activity
** <<7>> - Self-Repairing Learning Rule for Spiking Astrocyte-Neuron Networks
This paper explores a self-repairing effect at the tripartied synapse mediated
by astrocytes, and extends this idea by proposing a STDP/BCM learning rule that
is capable of fault tolerance.

Their model consists of an LIF neuron
$T_m \frac{dv}{dt} = -v(t) + Rm\Sigma_{i=1}^{n} I^i_{syn}(t)$

$T_m$ is the neuron membrane time constant, $v(t)$ is the membrane potential.
$R_m$ is the membrane resistance, $I^i_{syn}(t)$ is the current contribution
from the i-th synapse. $n$ is the number of synapses. When $v > v_{th}$ the
neuron fires, and goes to a reset state for a refractory period of 2ms.

A learning rule, which is a combination of STPD and BCM (called BCM-STDP) is
described. For the STDP portion

\[ \begin{cases}
      A_0 exp(\frac{\Delta t}{\Tau_+}) & \Delat t \leq 0 \\
      - A_0 exp(\frac{\Delta t}{\Tau_-}) & \Delat t > 0
   \end{cases}
\]

The BCM portion controls the learning rate $A_0$ according to the following.
$A_0 = \frac{A}{1 + exp(\alpha(f-f_0))} - A_-$

experimentally $\alpha$ has been determined to be $0.1$. $f$ and $f_0$ are the
target and actual firing rates.

A few different senairos are tested with the same topology.

n1 --
     \----- Astro
      n3
	 /----- Astro
n2 --

n1 -> n3 and n2 -> n3 connections actually consists of 8 synapses

In the no fault case, 25 Hz inputs are provided to n1 and n2, and the target
firing rate for BCM was also set to 25 Hz. Results showed that synaptic weights
were potentiated as expected. Inputs not in close proximity to 25 Hz range
showed no learning (as expected per BCM rules)

In the fault case, 6 of the 8 synapses connecting n2 -> n3 were cut. In
simulation, it is shown that the astrocytes are able to compensate for this by
upping the weights, and restore the post-damage firing rate.


** <<8>> - Effects of astrocyte on weak signal detection performance of Hodgkin–Huxley neuron
"Allegrini et al. [21]
proposed a computationally simple network model of mutual neuron–astrocyte
interactions and showed that the neural synchronization established in the
absence of astrocyte in the network is effectively broken by neuron–astrocyte
interactions."

"De Pitta et al. [25] showed 
that astrocytic effects on the synaptic plasticity can be
controlled by the frequency of calcium oscillations in
astrocyte."

Astrocytes Model
----------------
Action potentials are detected and resulting ^ca+ through a pesudo-IPC3 pathway
Ca2+ dynamics are modeled in a bio-plausible way using leak, pump, and gate
currents.


** <<9>> - Bidirectional Coupling between Astrocytes and Neurons Mediates Learning and Dynamic Coordination in the Brain

Astrocytes can Encapsulate 10^5 synapses

Astrocyte <-> Astrocyte communication may be related to IP3 diffusion between
Astrocytes

Slow-Indward-Currents (SICs) rise over the course of about 60ms and decay over
about 600ms.

Synchronization may be mediated by the release of glutamate at two separate
locations of the same Astrocyte. Based on the lack of overlap within an
Astrocyte's domain, and the time-scale of Astro <-> Astro communication this
release (for the purpose of synchronization) is likely isolated to a single
astrocyte.

Research explores how local activity can results in plasticity at remote sites
via SICs. SICs are used in the SGNN to synchronize neurons and provide teaching
signals.

Astrocyte Ca2+ concentration doesn't increase continuously. After a certain
threshold there is Ca2+ mediated Ca2+ release, which results in an
oscillation. This is modeled by a gatekeeping signal f, which dampens
pre-synaptic activity.

Tripartite Synapse Model
------------------------
The Tsodykes Dynamic Synapse Model (y) is used between pre-synaptic input and
weight. The STDP block considers the pre-synaptic and post-neuron signals for
learning. The Neuron->Astrocyte comms happen post-Tsodykes but pre-weight. SICs
affect the neuron directly. There is a pre-synaptic inhibition effect, which
affects the Tsodykes synapse model.

There is depolarization-induced suppression of pre-synaptic activity, caused by
neurotransmitters released at the post-synaptic dendrite.

This research considers both the 'Gatekeeper' and 'Nadkarni and Jung' astrocyte
interaction models.

When considering multiple inputs to an Astrocyte, the total [Ca2+] is a sum of
the individual calcium values associated with each synapse (diffusion dynamtics
are ignored).

Effect on STDP/Learning
-----------------------
Astrocytes can create a bridge between synapses, and be configured in such a way
that one synapse provides a supervisory signal to another (in the form of
SICs). In such a configuration STDP can be driven by the astrocyte SIC, even
when the weight and pre-synaptic activity wouldn't have been sufficient to drive
post-synaptic spikes.

Experiments
-----------
Establishing valid input frequency ranges that result in [Ca2+] oscillations


*** TODO References to Look into
[30] - Gatekeeper
[31,32] - Nadkarni and Jung model
[33] - Rinzel Ca2+ dynamics  2+
[66] - Review of synaptic plasticity models
[19,20,80-89]

